-- CREATE WAREHOUSE
CREATE OR REPLACE WAREHOUSE PARIS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD';

-- CREATE DATABASE
CREATE DATABASE PARIS_IMMO;

-- CREATE RAW, NORMALIZATION AND DENORM SCHEMAS
CREATE SCHEMA PARIS_IMMO.RAW;
CREATE SCHEMA PARIS_IMMO.NORMALIZED;
CREATE SCHEMA PARIS_IMMO.DENORM;

USE SCHEMA PARIS_IMMO.RAW

-- CREATE A STAGE FOR UPLOADING LOCAL FILES
CREATE OR REPLACE STAGE PARIS_IMMO.RAW.STAGE_RAW;

-- VERIFY THE FILE IS IN THE STAGE THAT IS UPLOADED THROUGH SNOWSQL IN TERMINAL
LIST @PARIS_IMMO.RAW.STAGE_RAW;

-- CREATE RAW TABLE

CREATE TABLE IF NOT EXISTS PARIS_IMMO.RAW.DVF_RAW (
    ID_MUTATION VARCHAR,
    DATE_MUTATION VARCHAR,
    NATURE_MUTATION VARCHAR,
    VALEUR_FONCIERE VARCHAR,
    CODE_POSTAL VARCHAR,
    CODE_COMMUNE VARCHAR,
    NOM_COMMUNE VARCHAR,
    CODE_DEPARTEMENT VARCHAR,
    NOMBRE_LOTS VARCHAR,
    TYPE_LOCAL VARCHAR,
    SURFACE_REELLE_BATI VARCHAR,
    NOMBRE_PIECES_PRINCIPALES VARCHAR,
    SURFACE_TERRAIN VARCHAR,
    LONGITUDE VARCHAR,
    LATITUDE VARCHAR
);

CREATE TABLE IF NOT EXISTS PARIS_IMMO.RAW.RENT_RAW (
    CODE_GRAND_QUARTIER VARCHAR,
    NOM_QUARTIER VARCHAR,
    ANNEE VARCHAR,
    PIECE VARCHAR,
    REF VARCHAR,
    MAX VARCHAR,
    MIN VARCHAR,
    GEO_POINT_2D VARCHAR,
    GEO_SHAPE VARCHAR,
    TYPE_LOCATION VARCHAR,
    EPOQUE_CONSTRUCTION VARCHAR
);


CREATE TABLE IF NOT EXISTS PARIS_IMMO.RAW.POPULATION_RAW (
    COM_ARM_CODE VARCHAR,
    COM_ARM_NAME VARCHAR,
    COM_ARM_POP_MUN VARCHAR,
    START_YEAR VARCHAR,
    DEP_CODE VARCHAR
);

CREATE TABLE IF NOT EXISTS PARIS_IMMO.RAW.HOUSING_RAW (
    NUM_DAU VARCHAR,
    DATE_REELLE_AUTORISATION VARCHAR,
    TYPE_DAU VARCHAR,
    NATURE_PROJET_COMPLETEE VARCHAR,
    NB_LGT_TOT_CREES VARCHAR,
    SURF_HAB_CREEE VARCHAR,
    ADR_CODPOST_TER VARCHAR,
    DEP_CODE VARCHAR
);

CREATE TABLE IF NOT EXISTS PARIS_IMMO.RAW.NONHOUSING_RAW (
    NUM_DAU VARCHAR,
    DATE_REELLE_AUTORISATION VARCHAR,
    TYPE_DAU VARCHAR,
    NATURE_PROJET_COMPLETEE VARCHAR,
    SURF_LOC_CREEE VARCHAR,
    ADR_CODPOST_TER VARCHAR,
    DEP_CODE VARCHAR
);

CREATE TABLE IF NOT EXISTS PARIS_IMMO.RAW.COMPANY_RAW (
    SIRET VARCHAR,
    SIREN VARCHAR,
    DATECREATIONETABLISSEMENT VARCHAR,
    ETATADMINISTRATIFETABLISSEMENT VARCHAR,
    ACTIVITEPRINCIPALE_ETABLISSEMENT VARCHAR,
    TRANCHEEFFECTIFSETABLISSEMENT VARCHAR,
    CODEPOSTALETABLISSEMENT VARCHAR,
    LIBELLECOMMUNEETABLISSEMENT VARCHAR,
    CODECOMMUNEETABLISSEMENT VARCHAR,
    NUMEROVOIEETABLISSEMENT VARCHAR,
    TYPEVOIEETABLISSEMENT VARCHAR,
    LIBELLEVOIEETABLISSEMENT VARCHAR,
    DATEDERNIERTRAITEMENTETABLISSEMENT VARCHAR
);

CREATE TABLE IF NOT EXISTS PARIS_IMMO.RAW.NAF_RAW (
    MAIN_ACTIVITY_CODE VARCHAR,
    ACTIVITY_LABEL VARCHAR
);

-- COPY THE RAW DATA INTO RAW TABLE

TRUNCATE TABLE PARIS_IMMO.RAW.DVF_RAW;

COPY INTO PARIS_IMMO.RAW.DVF_RAW (
    ID_MUTATION,
    DATE_MUTATION,
    NATURE_MUTATION,
    VALEUR_FONCIERE,
    CODE_POSTAL,
    CODE_COMMUNE,
    NOM_COMMUNE,
    CODE_DEPARTEMENT,
    NOMBRE_LOTS,
    TYPE_LOCAL,
    SURFACE_REELLE_BATI,
    NOMBRE_PIECES_PRINCIPALES,
    SURFACE_TERRAIN,
    LONGITUDE,
    LATITUDE
)
FROM (
    SELECT 
        $1,   -- id_mutation
        $2,   -- date_mutation
        $4,   -- nature_mutation
        $5,   -- valeur_fonciere
        $10,  -- code_postal
        $11,  -- code_commune
        $12,  -- nom_commune
        $13,  -- code_departement
        $30,  -- nombre_lots
        $31,  -- type_local
        $32,  -- surface_reelle_bati
        $33,  -- nombre_pieces_principales
        $38,  -- surface_terrain
        $39,  -- longitude
        $40   -- latitude
    FROM @PARIS_IMMO.RAW.STAGE_RAW/dvf.csv.gz
)
FILE_FORMAT = (FORMAT_NAME = PARIS_IMMO.RAW.FMT_COMMA) ON_ERROR = 'CONTINUE' FORCE = TRUE;

DELETE FROM PARIS_IMMO.RAW.DVF_RAW WHERE CODE_DEPARTEMENT != '75';

TRUNCATE TABLE PARIS_IMMO.RAW.RENT_RAW;

COPY INTO PARIS_IMMO.RAW.RENT_RAW (
    CODE_GRAND_QUARTIER,
    NOM_QUARTIER,
    ANNEE,
    PIECE,
    REF,
    MAX,
    MIN,
    GEO_POINT_2D,
    GEO_SHAPE,
    TYPE_LOCATION,
    EPOQUE_CONSTRUCTION
)
FROM (
    SELECT
        $12,   -- CODE_GRAND_QUARTIER (INSEE code)
        $4,    -- NOM_QUARTIER
        $1,    -- ANNEE
        $5,    -- PIECE (Nombre de pièces principales)
        $8,    -- REF (Loyer de référence)
        $9,    -- MAX (Loyer majoré)
        $10,   -- MIN (Loyer minoré)
        $14,   -- GEO_POINT_2D
        $13,   -- GEO_SHAPE
        $7,    -- TYPE_LOCATION (meublé / non meublé)
        $6     -- EPOQUE_CONSTRUCTION
    FROM @PARIS_IMMO.RAW.STAGE_RAW/rent_control.csv.gz
)
FILE_FORMAT = (FORMAT_NAME = PARIS_IMMO.RAW.FMT_SEMICOLON)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

TRUNCATE TABLE PARIS_IMMO.RAW.POPULATION_RAW;

COPY INTO PARIS_IMMO.RAW.POPULATION_RAW (
    COM_ARM_CODE,
    COM_ARM_NAME,
    COM_ARM_POP_MUN,
    START_YEAR,
    DEP_CODE
)
FROM (
    SELECT
        $3,   -- COM_ARM_CODE
        $4,   -- COM_ARM_NAME
        $5,   -- COM_ARM_POP_MUN
        $11,  -- START_YEAR
        $8    -- DEP_CODE
    FROM @PARIS_IMMO.RAW.STAGE_RAW/population.csv.gz
)
FILE_FORMAT = (FORMAT_NAME = PARIS_IMMO.RAW.FMT_SEMICOLON)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

TRUNCATE TABLE PARIS_IMMO.RAW.HOUSING_RAW;

COPY INTO PARIS_IMMO.RAW.HOUSING_RAW (
    NUM_DAU,
    DATE_REELLE_AUTORISATION,
    TYPE_DAU,
    NATURE_PROJET_COMPLETEE,
    NB_LGT_TOT_CREES,
    SURF_HAB_CREEE,
    ADR_CODPOST_TER,
    DEP_CODE
)
FROM (
    SELECT
        $7,    -- NUM_DAU
        $9,    -- DATE_REELLE_AUTORISATION
        $6,    -- TYPE_DAU
        $8,    -- NATURE_PROJET_COMPLETEE
        $37,   -- NB_LGT_TOT_CREES
        $36,   -- SURF_HAB_CREEE
        $22,   -- ADR_CODPOST_TER
        $3     -- DEP_CODE
    FROM @PARIS_IMMO.RAW.STAGE_RAW/housing.csv.gz
)
FILE_FORMAT = (FORMAT_NAME = PARIS_IMMO.RAW.FMT_SEMICOLON)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

TRUNCATE TABLE PARIS_IMMO.RAW.NONHOUSING_RAW;

COPY INTO PARIS_IMMO.RAW.NONHOUSING_RAW (
    NUM_DAU,
    DATE_REELLE_AUTORISATION,
    TYPE_DAU,
    NATURE_PROJET_COMPLETEE,
    SURF_LOC_CREEE,
    ADR_CODPOST_TER,
    DEP_CODE
)
FROM (
    SELECT
        $7,    -- NUM_DAU
        $9,    -- DATE_REELLE_AUTORISATION
        $6,    -- TYPE_DAU
        $8,    -- NATURE_PROJET_COMPLETEE
        $36,   -- SURF_LOC_CREEE
        $22,   -- ADR_CODPOST_TER
        $3     -- DEP_CODE
    FROM @PARIS_IMMO.RAW.STAGE_RAW/NonHousing.csv.gz
)
FILE_FORMAT = (FORMAT_NAME = PARIS_IMMO.RAW.FMT_SEMICOLON)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

TRUNCATE TABLE PARIS_IMMO.RAW.COMPANY_RAW;

COPY INTO PARIS_IMMO.RAW.COMPANY_RAW (
    SIREN,
    SIRET,
    DATECREATIONETABLISSEMENT,
    ETATADMINISTRATIFETABLISSEMENT,
    ACTIVITEPRINCIPALE_ETABLISSEMENT,
    TRANCHEEFFECTIFSETABLISSEMENT,
    CODEPOSTALETABLISSEMENT,
    LIBELLECOMMUNEETABLISSEMENT,
    CODECOMMUNEETABLISSEMENT,
    NUMEROVOIEETABLISSEMENT,
    TYPEVOIEETABLISSEMENT,
    LIBELLEVOIEETABLISSEMENT,
    DATEDERNIERTRAITEMENTETABLISSEMENT
)
FROM (
    SELECT
        $1,   -- siren
        $3,   -- siret
        $5,   -- dateCreationEtablissement
        $46,  -- etatAdministratifEtablissement
        $51,  -- activitePrincipaleEtablissement
        $6,   -- trancheEffectifsEtablissement
        $19,  -- codePostalEtablissement
        $20,  -- libelleCommuneEtablissement
        $23,  -- codeCommuneEtablissement
        $13,  -- numeroVoieEtablissement
        $17,  -- typeVoieEtablissement
        $18,  -- libelleVoieEtablissement
        $9    -- dateDernierTraitementEtablissement
    FROM @PARIS_IMMO.RAW.STAGE_RAW/company_activity.csv.gz
)
FILE_FORMAT = (FORMAT_NAME = PARIS_IMMO.RAW.FMT_COMMA)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;


TRUNCATE TABLE PARIS_IMMO.RAW.NAF_RAW;

COPY INTO PARIS_IMMO.RAW.NAF_RAW
FROM @PARIS_IMMO.RAW.STAGE_RAW/activity_label.csv.gz
FILE_FORMAT = (FORMAT_NAME = PARIS_IMMO.RAW.FMT_COMMA)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;
