USE WAREHOUSE PARIS_WH;
USE DATABASE PARIS_IMMO;
USE SCHEMA PARIS_IMMO.NORMALIZED;



-- ENTITIES

CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.DIM_YEAR (
    YEAR NUMBER(38,0) NOT NULL,
    PRIMARY KEY (YEAR)
);

CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.DIM_ARRONDISSEMENT (
    ARRONDISSEMENT_CODE NUMBER(38,0) NOT NULL,
    ARRONDISSEMENT_NAME VARCHAR NOT NULL,
    PRIMARY KEY (ARRONDISSEMENT_CODE)
);

CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.DIM_NEIGHBOURHOOD (
    NEIGHBOURHOOD_ID        NUMBER(38,0)  NOT NULL,
    ARRONDISSEMENT_CODE     NUMBER(38,0)  NOT NULL,
    NEIGHBOURHOOD_NAME      VARCHAR       NOT NULL,
    CENTROID_LAT            FLOAT,
    CENTROID_LON            FLOAT,
    GEOMETRY_WKT            VARCHAR,
    

    PRIMARY KEY (NEIGHBOURHOOD_ID)
);

CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.DIM_CONSTRUCTION_PERIOD (
    CONSTRUCTION_PERIOD_ID INT PRIMARY KEY,
    CONSTRUCTION_PERIOD_LABEL STRING UNIQUE
);

CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.DIM_FURNISHED_STATUS (
    FURNISHED_STATUS_ID INT PRIMARY KEY,
    FURNISHED_STATUS_LABEL STRING UNIQUE
);

CREATE OR REPLACE TABLE EXISTS PARIS_IMMO.NORMALIZED.DIM_ACTIVITY (
    MAIN_ACTIVITY_CODE VARCHAR NOT NULL,
    ACTIVITY_LABEL VARCHAR NOT NULL,
    PRIMARY KEY (MAIN_ACTIVITY_CODE)
);

CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.PERMIT_TYPE_LOOKUP (
    PERMIT_TYPE VARCHAR NOT NULL,
    PERMIT_TYPE_LABEL VARCHAR,
    PRIMARY KEY (PERMIT_TYPE)
);

CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.PROJECT_TYPE_LOOKUP (
    PROJECT_TYPE INT NOT NULL,
    PROJECT_TYPE_LABEL VARCHAR,
    PRIMARY KEY (PROJECT_TYPE)
);

-- DVF TRANSACTION
CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.FACT_TRANSACTION (
    TRANSACTION_ID VARCHAR NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    ARRONDISSEMENT_CODE NUMBER(38,0) NOT NULL,
    YEAR NUMBER(38,0) NOT NULL,
    TOTAL_BUILT_AREA FLOAT,
    NB_ROOMS NUMBER(38,0),
    PROPERTY_VALUE FLOAT,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FK_FACT_ARRONDISSEMENT FOREIGN KEY (ARRONDISSEMENT_CODE) REFERENCES PARIS_IMMO.NORMALIZED.DIM_ARRONDISSEMENT(ARRONDISSEMENT_CODE),
    CONSTRAINT FK_FACT_YEAR FOREIGN KEY (YEAR) REFERENCES PARIS_IMMO.NORMALIZED.DIM_YEAR(YEAR)
);

-- RENT CONTROL 
CREATE OR REPLACE TABLE  PARIS_IMMO.NORMALIZED.FACT_RENT (
    RENT_ID VARCHAR NOT NULL,

    NEIGHBOURHOOD_ID NUMBER(38,0) NOT NULL,
    YEAR NUMBER(38,0) NOT NULL,
    NB_ROOMS NUMBER(38,0) NOT NULL,

    CONSTRUCTION_PERIOD_ID NUMBER(38,0) NOT NULL,
    FURNISHED_STATUS_ID NUMBER(38,0) NOT NULL,

    RENT_REF FLOAT,
    RENT_REF_UPPER FLOAT,
    RENT_REF_LOWER FLOAT,

    PRIMARY KEY (RENT_ID),

    CONSTRAINT FK_RENT_NEIGHBOURHOOD
        FOREIGN KEY (NEIGHBOURHOOD_ID)
        REFERENCES PARIS_IMMO.NORMALIZED.DIM_NEIGHBOURHOOD(NEIGHBOURHOOD_ID),

    CONSTRAINT FK_RENT_YEAR
        FOREIGN KEY (YEAR)
        REFERENCES PARIS_IMMO.NORMALIZED.DIM_YEAR(YEAR),

    CONSTRAINT FK_RENT_CONSTRUCTION_PERIOD
        FOREIGN KEY (CONSTRUCTION_PERIOD_ID)
        REFERENCES PARIS_IMMO.NORMALIZED.DIM_CONSTRUCTION_PERIOD(CONSTRUCTION_PERIOD_ID),

    CONSTRAINT FK_RENT_FURNISHED_STATUS
        FOREIGN KEY (FURNISHED_STATUS_ID)
        REFERENCES PARIS_IMMO.NORMALIZED.DIM_FURNISHED_STATUS(FURNISHED_STATUS_ID)
);
-- POPULATION GROWTH

CREATE OR REPLACE PARIS_IMMO.NORMALIZED.FACT_GROWTH (
    ARRONDISSEMENT_CODE NUMBER(38,0) NOT NULL,
    YEAR NUMBER(38,0) NOT NULL,
    POPULATION_MUNICIPAL NUMBER(38,0),
    PRIMARY KEY (ARRONDISSEMENT_CODE, YEAR),
    CONSTRAINT FK_GROWTH_ARRONDISSEMENT FOREIGN KEY (ARRONDISSEMENT_CODE) REFERENCES PARIS_IMMO.NORMALIZED.DIM_ARRONDISSEMENT(ARRONDISSEMENT_CODE),
    CONSTRAINT FK_GROWTH_YEAR FOREIGN KEY (YEAR) REFERENCES PARIS_IMMO.NORMALIZED.DIM_YEAR(YEAR)
);

CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.FACT_HOUSING_PERMIT (
    PERMIT_ID VARCHAR NOT NULL,
    AUTHORIZATION_DATE DATE,
    ARRONDISSEMENT_CODE NUMBER(38,0) NOT NULL,
    YEAR NUMBER(38,0),
    PERMIT_TYPE VARCHAR,
    PROJECT_TYPE INT,
    HOUSING_UNITS_CREATED NUMBER(38,0),
    SURFACE_CREATED FLOAT,
    PRIMARY KEY (PERMIT_ID),
    CONSTRAINT FK_HOUSING_ARRONDISSEMENT FOREIGN KEY (ARRONDISSEMENT_CODE) REFERENCES PARIS_IMMO.NORMALIZED.DIM_ARRONDISSEMENT(ARRONDISSEMENT_CODE),
    CONSTRAINT FK_HOUSING_PROJECT_TYPE FOREIGN KEY (PROJECT_TYPE) REFERENCES PARIS_IMMO.NORMALIZED.PROJECT_TYPE_LOOKUP(PROJECT_TYPE),
    CONSTRAINT FK_HOUSING_PERMIT_TYPE FOREIGN KEY (PERMIT_TYPE) REFERENCES PARIS_IMMO.NORMALIZED.PERMIT_TYPE_LOOKUP(PERMIT_TYPE),
     CONSTRAINT FK_FACT_YEAR FOREIGN KEY (YEAR) REFERENCES PARIS_IMMO.NORMALIZED.DIM_YEAR(YEAR)
);

-- NONHOUSING PERMITS
CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.FACT_NONHOUSING_PERMIT (
    PERMIT_ID VARCHAR NOT NULL,
    AUTHORIZATION_DATE DATE,
    ARRONDISSEMENT_CODE NUMBER(38,0) NOT NULL,
    YEAR NUMBER(38,0),
    PERMIT_TYPE VARCHAR,
    PROJECT_TYPE INT,
    HOUSING_UNITS_CREATED NUMBER(38,0),
    SURFACE_CREATED FLOAT,
    PRIMARY KEY (PERMIT_ID),
    CONSTRAINT FK_HOUSING_ARRONDISSEMENT FOREIGN KEY (ARRONDISSEMENT_CODE)        REFERENCES PARIS_IMMO.NORMALIZED.DIM_ARRONDISSEMENT(ARRONDISSEMENT_CODE),
    CONSTRAINT FK_NONHOUSING_PROJECT_TYPE FOREIGN KEY (PROJECT_TYPE) 
    REFERENCES PARIS_IMMO.NORMALIZED.PROJECT_TYPE_LOOKUP(PROJECT_TYPE),
    CONSTRAINT FK_NONHOUSING_PERMIT_TYPE FOREIGN KEY (PERMIT_TYPE) 
    REFERENCES PARIS_IMMO.NORMALIZED.PERMIT_TYPE_LOOKUP(PERMIT_TYPE),
    CONSTRAINT FK_FACT_YEAR FOREIGN KEY (YEAR) REFERENCES PARIS_IMMO.NORMALIZED.DIM_YEAR(YEAR)
);

CREATE OR REPLACE TABLE PARIS_IMMO.NORMALIZED.FACT_COMPANY_ACTIVITY (
    ESTABLISHMENT_ID VARCHAR NOT NULL,
    ESTABLISHMENT_CREATION_DATE DATE,
    ARRONDISSEMENT_CODE NUMBER(38,0) NOT NULL,
    MAIN_ACTIVITY_CODE VARCHAR,
    ADMINISTRATIVE_STATUS VARCHAR,
    EMPLOYEE_SIZE_BRACKET VARCHAR,
    YEAR NUMBER(38,0),
    YEAR_CLOSED NUMBER(38,0),
    PRIMARY KEY (ESTABLISHMENT_ID),
    CONSTRAINT FK_COMPANY_ARRONDISSEMENT FOREIGN KEY (ARRONDISSEMENT_CODE) REFERENCES PARIS_IMMO.NORMALIZED.DIM_ARRONDISSEMENT(ARRONDISSEMENT_CODE),
    CONSTRAINT FK_COMPANY_ACTIVITY FOREIGN KEY (MAIN_ACTIVITY_CODE) REFERENCES PARIS_IMMO.NORMALIZED.DIM_ACTIVITY(MAIN_ACTIVITY_CODE),
    CONSTRAINT FK_FACT_YEAR FOREIGN KEY (YEAR) REFERENCES PARIS_IMMO.NORMALIZED.DIM_YEAR(YEAR)
);


------POPULATE THE TABLE BY PERFORMING TRANSFORMATION------------

-- DIM_YEAR
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.DIM_YEAR;
INSERT INTO PARIS_IMMO.NORMALIZED.DIM_YEAR
SELECT DISTINCT YEAR(TRY_TO_DATE(date_mutation)) AS yr
FROM   PARIS_IMMO.RAW.DVF_RAW
WHERE  date_mutation IS NOT NULL
  AND  YEAR(TRY_TO_DATE(date_mutation)) BETWEEN 2020 AND 2025;

-- DIM_ARRONDISSEMENT

TRUNCATE TABLE PARIS_IMMO.NORMALIZED.DIM_ARRONDISSEMENT;

INSERT INTO PARIS_IMMO.NORMALIZED.DIM_ARRONDISSEMENT
    (ARRONDISSEMENT_CODE, ARRONDISSEMENT_NAME)
SELECT DISTINCT
    TRY_CAST(COM_ARM_CODE AS INT) AS ARRONDISSEMENT_CODE,
    COM_ARM_NAME AS ARRONDISSEMENT_NAME
FROM PARIS_IMMO.RAW.POPULATION_RAW
WHERE COM_ARM_CODE IS NOT NULL
  AND COM_ARM_NAME IS NOT NULL
  AND DEP_CODE = '75'
ORDER BY ARRONDISSEMENT_CODE;

-- DIM_NEIGHBOURHOOD
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.DIM_NEIGHBOURHOOD;

INSERT INTO PARIS_IMMO.NORMALIZED.DIM_NEIGHBOURHOOD
    (NEIGHBOURHOOD_ID,
     ARRONDISSEMENT_CODE,
     NEIGHBOURHOOD_NAME,
     CENTROID_LAT,
     CENTROID_LON,
     GEOMETRY_WKT)
SELECT DISTINCT
    TRY_CAST(CODE_GRAND_QUARTIER AS INT) AS NEIGHBOURHOOD_ID,
    TRY_CAST(LEFT(CODE_GRAND_QUARTIER, 5) AS INT) AS ARRONDISSEMENT_CODE,
    NOM_QUARTIER AS NEIGHBOURHOOD_NAME,
    TRY_CAST(SPLIT_PART(GEO_POINT_2D, ',', 1) AS FLOAT) AS CENTROID_LAT,
    TRY_CAST(SPLIT_PART(GEO_POINT_2D, ',', 2) AS FLOAT) AS CENTROID_LON,
    ST_ASWKT(TRY_TO_GEOGRAPHY(GEO_SHAPE)) AS GEOMETRY_WKT
FROM PARIS_IMMO.RAW.RENT_RAW
WHERE CODE_GRAND_QUARTIER IS NOT NULL
  AND NOM_QUARTIER IS NOT NULL;


-- DIM_CONSTRUCTION_PERIOD
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.DIM_CONSTRUCTION_PERIOD;
INSERT INTO PARIS_IMMO.NORMALIZED.DIM_CONSTRUCTION_PERIOD
SELECT
    ROW_NUMBER() OVER (ORDER BY CONSTRUCTION_PERIOD) AS CONSTRUCTION_PERIOD_ID,
    CONSTRUCTION_PERIOD
FROM (
    SELECT DISTINCT
        EPOQUE_CONSTRUCTION AS CONSTRUCTION_PERIOD
    FROM PARIS_IMMO.RAW.RENT_RAW
    WHERE EPOQUE_CONSTRUCTION IS NOT NULL
);


-- DIM_FURNISHED_STATUS
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.DIM_FURNISHED_STATUS;
INSERT INTO PARIS_IMMO.NORMALIZED.DIM_FURNISHED_STATUS
SELECT
    ROW_NUMBER() OVER (ORDER BY FURNISHED_STATUS) AS FURNISHED_STATUS_ID,
    FURNISHED_STATUS
FROM (
    SELECT DISTINCT
        CASE
            WHEN LOWER(TYPE_LOCATION) = 'meublé' THEN 'FURNISHED'
            WHEN LOWER(TYPE_LOCATION) = 'non meublé' THEN 'UNFURNISHED'
            ELSE TYPE_LOCATION
        END AS FURNISHED_STATUS
    FROM PARIS_IMMO.RAW.RENT_RAW
    WHERE TYPE_LOCATION IS NOT NULL
);

--DIM_ACTIVITY
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.DIM_ACTIVITY;

INSERT INTO PARIS_IMMO.NORMALIZED.DIM_ACTIVITY
    (MAIN_ACTIVITY_CODE, ACTIVITY_LABEL)
SELECT DISTINCT
    MAIN_ACTIVITY_CODE,
    ACTIVITY_LABEL
FROM PARIS_IMMO.RAW.NAF_RAW
WHERE MAIN_ACTIVITY_CODE IS NOT NULL
  AND ACTIVITY_LABEL IS NOT NULL;

-- PERMIT_TYPE_LOOKUP
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.PERMIT_TYPE_LOOKUP;

INSERT INTO PARIS_IMMO.NORMALIZED.PERMIT_TYPE_LOOKUP
    (PERMIT_TYPE, PERMIT_TYPE_LABEL)
VALUES
    ('PC', 'Permit for Construction'),
    ('DP', 'Prior Declaration'),
    ('PA', 'Land Development Permit');

-- PROJECT_TYPE_LOOKUP
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.PROJECT_TYPE_LOOKUP;
INSERT INTO PARIS_IMMO.NORMALIZED.PROJECT_TYPE_LOOKUP VALUES
    (0, 'Unknown'),
    (1, 'New construction'),
    (2, 'Transformation without extension or reduction of surface area'),
    (3, 'Transformation with surface extension'),
    (4, 'Transformation with reduced surface area'),
    (5, 'Untransformed surface extension'),
    (6, 'Area decrease without transformation');


    -- FACT_TRANSACTION
    TRUNCATE TABLE PARIS_IMMO.NORMALIZED.FACT_TRANSACTION;

INSERT INTO PARIS_IMMO.NORMALIZED.FACT_TRANSACTION
    (TRANSACTION_ID,
     TRANSACTION_DATE,
     ARRONDISSEMENT_CODE,
     YEAR,
     TOTAL_BUILT_AREA,
     NB_ROOMS,
     PROPERTY_VALUE,
     LATITUDE,
     LONGITUDE)
WITH RAW AS (
    SELECT *
    FROM PARIS_IMMO.RAW.DVF_RAW
    WHERE NATURE_MUTATION = 'Vente'
      AND TRY_CAST(VALEUR_FONCIERE AS FLOAT) > 0
      AND CODE_DEPARTEMENT = '75'
),
INDICATORS AS (
    SELECT *,
        CASE WHEN TYPE_LOCAL = 'Maison' THEN 1 ELSE 0 END AS IS_MAISON,
        CASE WHEN TYPE_LOCAL = 'Appartement' THEN 1 ELSE 0 END AS IS_APPARTEMENT,
        CASE WHEN TYPE_LOCAL = 'Dépendance' THEN 1 ELSE 0 END AS IS_DEPENDANCE,
        CASE WHEN TYPE_LOCAL = 'Local industriel. commercial ou assimilé'
             THEN 1 ELSE 0 END AS IS_LOCAL_INDUSTRIEL,
        CASE WHEN TYPE_LOCAL IN ('Maison','Appartement',
                                 'Local industriel. commercial ou assimilé')
             THEN TRY_CAST(SURFACE_REELLE_BATI AS FLOAT)
             ELSE NULL END AS SURFACE_BATI_FOR_AGG
    FROM RAW
),
AGG AS (
    SELECT
        ID_MUTATION,
        MAX(TRY_TO_DATE(DATE_MUTATION)) AS TRANSACTION_DATE,
        MAX(TRY_CAST(VALEUR_FONCIERE AS FLOAT)) AS PROPERTY_VALUE,
        SUM(COALESCE(SURFACE_BATI_FOR_AGG, 0)) AS TOTAL_BUILT_AREA,
        SUM(TRY_CAST(NOMBRE_PIECES_PRINCIPALES AS INT)) AS NB_ROOMS,
        SUM(IS_MAISON) AS NB_MAISONS,
        SUM(IS_APPARTEMENT) AS NB_APPARTEMENTS,
        SUM(IS_DEPENDANCE) AS NB_DEPENDANCES,
        SUM(IS_LOCAL_INDUSTRIEL) AS NB_LOCAUX_INDUSTRIELS,
        MAX(CODE_COMMUNE) AS CODE_COMMUNE,
        MAX(LATITUDE) AS LATITUDE,
        MAX(LONGITUDE) AS LONGITUDE
    FROM INDICATORS
    GROUP BY ID_MUTATION
),
WITH_ARR AS (
    SELECT *,
        CASE
            WHEN LEFT(CODE_COMMUNE, 2) = '75'
             AND LENGTH(CODE_COMMUNE) = 5
            THEN TRY_CAST('751' || LPAD(RIGHT(CODE_COMMUNE, 2), 2, '0') AS INT)
            ELSE NULL
        END AS ARRONDISSEMENT_CODE,
        YEAR(TRANSACTION_DATE) AS YEAR
    FROM AGG
),
FILTERED AS (
    SELECT *
    FROM WITH_ARR
    WHERE TOTAL_BUILT_AREA > 0
      AND NB_DEPENDANCES = 0
      AND NB_APPARTEMENTS = 1
      AND NB_MAISONS = 0
      AND NB_LOCAUX_INDUSTRIELS = 0
      AND ARRONDISSEMENT_CODE IS NOT NULL
      AND YEAR BETWEEN 2020 AND 2025
)
SELECT
    ID_MUTATION,
    TRANSACTION_DATE,
    ARRONDISSEMENT_CODE,
    YEAR,
    TOTAL_BUILT_AREA,
    CAST(NB_ROOMS AS INT),
    PROPERTY_VALUE,
    TRY_CAST(LATITUDE AS FLOAT),
    TRY_CAST(LONGITUDE AS FLOAT)
FROM FILTERED
WHERE ID_MUTATION IS NOT NULL;


--FACT_RENT


TRUNCATE TABLE PARIS_IMMO.NORMALIZED.FACT_RENT;

INSERT INTO PARIS_IMMO.NORMALIZED.FACT_RENT
SELECT
    MD5(CONCAT_WS('|',
        R.CODE_GRAND_QUARTIER,
        R.ANNEE,
        R.PIECE,
        R.EPOQUE_CONSTRUCTION,
        R.TYPE_LOCATION
    )) AS RENT_ID,

    TRY_CAST(R.CODE_GRAND_QUARTIER AS NUMBER(38,0)) AS NEIGHBOURHOOD_ID,
    TRY_CAST(R.ANNEE AS NUMBER(38,0)) AS YEAR,
    TRY_CAST(R.PIECE AS NUMBER(38,0)) AS NB_ROOMS,

    C.CONSTRUCTION_PERIOD_ID,
    F.FURNISHED_STATUS_ID,

    TRY_CAST(R.REF AS FLOAT) AS RENT_REF,
    TRY_CAST(R.MAX AS FLOAT) AS RENT_REF_UPPER,
    TRY_CAST(R.MIN AS FLOAT) AS RENT_REF_LOWER

FROM PARIS_IMMO.RAW.RENT_RAW R

LEFT JOIN PARIS_IMMO.NORMALIZED.DIM_CONSTRUCTION_PERIOD C
    ON R.EPOQUE_CONSTRUCTION = C.CONSTRUCTION_PERIOD_LABEL

LEFT JOIN PARIS_IMMO.NORMALIZED.DIM_FURNISHED_STATUS F
    ON CASE
        WHEN LOWER(R.TYPE_LOCATION) = 'meublé' THEN 'FURNISHED'
        WHEN LOWER(R.TYPE_LOCATION) = 'non meublé' THEN 'UNFURNISHED'
        ELSE R.TYPE_LOCATION
    END = F.FURNISHED_STATUS_LABEL

WHERE R.CODE_GRAND_QUARTIER IS NOT NULL
  AND R.ANNEE IS NOT NULL
  AND R.PIECE IS NOT NULL
  AND TRY_CAST(R.ANNEE AS INT) BETWEEN 2020 AND 2025;



--FACT_GROWTH
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.FACT_GROWTH;

INSERT INTO PARIS_IMMO.NORMALIZED.FACT_GROWTH
    (ARRONDISSEMENT_CODE,
     YEAR,
     POPULATION_MUNICIPAL)
SELECT
    TRY_CAST(COM_ARM_CODE AS INT) AS ARRONDISSEMENT_CODE,
    TRY_CAST(START_YEAR AS INT) AS YEAR,
    TRY_CAST(COM_ARM_POP_MUN AS INT) AS POPULATION_MUNICIPAL
FROM PARIS_IMMO.RAW.POPULATION_RAW
WHERE COM_ARM_CODE IS NOT NULL
  AND START_YEAR IS NOT NULL
  AND DEP_CODE = '75'
  AND TRY_CAST(START_YEAR AS INT) BETWEEN 2020 AND 2023;

--edit FACT_HOUSING 
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.FACT_HOUSING_PERMIT;

INSERT INTO PARIS_IMMO.NORMALIZED.FACT_HOUSING_PERMIT
    (PERMIT_ID,
     AUTHORIZATION_DATE,
     ARRONDISSEMENT_CODE,
     YEAR,
     PERMIT_TYPE,
     PROJECT_TYPE,
     HOUSING_UNITS_CREATED,
     SURFACE_CREATED)
WITH CLEANED AS (
    SELECT
        NUM_DAU AS PERMIT_ID,
        TRY_TO_DATE(DATE_REELLE_AUTORISATION) AS AUTHORIZATION_DATE,
        TYPE_DAU AS PERMIT_TYPE,
        COALESCE(NATURE_PROJET_COMPLETEE, '0') AS PROJECT_TYPE,
        TRY_CAST(NB_LGT_TOT_CREES AS INT) AS HOUSING_UNITS_CREATED,
        TRY_CAST(SURF_HAB_CREEE AS FLOAT) AS SURFACE_CREATED,
        CASE
            WHEN LEFT(ADR_CODPOST_TER, 2) = '75'
             AND LENGTH(ADR_CODPOST_TER) = 5
            THEN TRY_CAST('751' || LPAD(RIGHT(ADR_CODPOST_TER, 2), 2, '0') AS INT)
        END AS ARRONDISSEMENT_CODE,
        YEAR(TRY_TO_DATE(DATE_REELLE_AUTORISATION)) AS YR
    FROM PARIS_IMMO.RAW.HOUSING_RAW
    WHERE DEP_CODE = '75'
      AND NUM_DAU IS NOT NULL
),
DEDUPED AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY PERMIT_ID
            ORDER BY AUTHORIZATION_DATE DESC NULLS LAST
        ) AS RN
    FROM CLEANED
    WHERE ARRONDISSEMENT_CODE BETWEEN 75101 AND 75120
      AND YR BETWEEN 2020 AND 2025
)
SELECT
    PERMIT_ID,
    AUTHORIZATION_DATE,
    ARRONDISSEMENT_CODE,
    YR,
    PERMIT_TYPE,
    PROJECT_TYPE,
    HOUSING_UNITS_CREATED,
    SURFACE_CREATED
FROM DEDUPED
WHERE RN = 1;


-- FACT_NONHOUSING
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.FACT_NONHOUSING_PERMIT;

INSERT INTO PARIS_IMMO.NORMALIZED.FACT_NONHOUSING_PERMIT
    (PERMIT_ID,
     AUTHORIZATION_DATE,
     ARRONDISSEMENT_CODE,
     YEAR,
     PERMIT_TYPE,
     PROJECT_TYPE,
     SURFACE_CREATED)
WITH CLEANED AS (
    SELECT
        NUM_DAU AS PERMIT_ID,
        TRY_TO_DATE(DATE_REELLE_AUTORISATION) AS AUTHORIZATION_DATE,
        TYPE_DAU AS PERMIT_TYPE,
        NATURE_PROJET_COMPLETEE AS PROJECT_TYPE,
        TRY_CAST(SURF_LOC_CREEE AS FLOAT) AS SURFACE_CREATED,
        CASE
            WHEN LEFT(ADR_CODPOST_TER, 2) = '75'
             AND LENGTH(ADR_CODPOST_TER) = 5
            THEN TRY_CAST('751' || LPAD(RIGHT(ADR_CODPOST_TER, 2), 2, '0') AS INT)
        END AS ARRONDISSEMENT_CODE,
        YEAR(TRY_TO_DATE(DATE_REELLE_AUTORISATION)) AS YR
    FROM PARIS_IMMO.RAW.NONHOUSING_RAW
    WHERE DEP_CODE = '75'
      AND NUM_DAU IS NOT NULL
),
DEDUPED AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY PERMIT_ID
            ORDER BY AUTHORIZATION_DATE DESC NULLS LAST
        ) AS RN
    FROM CLEANED
    WHERE ARRONDISSEMENT_CODE BETWEEN 75101 AND 75120
      AND YR BETWEEN 2020 AND 2025
)
SELECT
    PERMIT_ID,
    AUTHORIZATION_DATE,
    ARRONDISSEMENT_CODE,
    YR,
    PERMIT_TYPE,
    PROJECT_TYPE,
    SURFACE_CREATED
FROM DEDUPED
WHERE RN = 1;

-- FACT_COMPANY_ACTIVITY
-- FACT_COMPANY_ACTIVITY
TRUNCATE TABLE PARIS_IMMO.NORMALIZED.FACT_COMPANY_ACTIVITY;
INSERT INTO PARIS_IMMO.NORMALIZED.FACT_COMPANY_ACTIVITY
    (ESTABLISHMENT_ID, ESTABLISHMENT_CREATION_DATE, ARRONDISSEMENT_CODE,
     MAIN_ACTIVITY_CODE, ADMINISTRATIVE_STATUS, EMPLOYEE_SIZE_BRACKET,
     YEAR, YEAR_CLOSED)
WITH cleaned AS (
    SELECT
        siret AS establishment_id,
        TRY_TO_DATE(dateCreationEtablissement) AS establishment_creation_date,
        CASE
            WHEN LEFT(codePostalEtablissement, 2) = '75'
             AND LENGTH(codePostalEtablissement) = 5
            THEN TRY_CAST('751' || LPAD(RIGHT(codePostalEtablissement,2),2,'0') AS INT)
        END AS arrondissement_code,
        ACTIVITEPRINCIPALE_ETABLISSEMENT AS main_activity_code,
        CASE etatAdministratifEtablissement
             WHEN 'A' THEN 'Active'
             WHEN 'F' THEN 'Closed'
             ELSE etatAdministratifEtablissement
        END AS administrative_status,
        trancheEffectifsEtablissement AS employee_size_bracket,
        YEAR(TRY_TO_DATE(dateCreationEtablissement)) AS yr,
        CASE WHEN etatAdministratifEtablissement = 'F'
             THEN YEAR(TRY_TO_DATE(dateDernierTraitementEtablissement))
        END AS year_closed
    FROM PARIS_IMMO.RAW.COMPANY_RAW
    WHERE siret IS NOT NULL
)
SELECT
    establishment_id, establishment_creation_date, arrondissement_code,
    main_activity_code, administrative_status, employee_size_bracket,
    yr, year_closed
FROM cleaned
WHERE arrondissement_code IS NOT NULL
  AND main_activity_code IS NOT NULL
  AND main_activity_code IN (SELECT MAIN_ACTIVITY_CODE FROM PARIS_IMMO.NORMALIZED.DIM_ACTIVITY)
  AND arrondissement_code BETWEEN 75101 AND 75120
  AND yr BETWEEN 2020 AND 2025
QUALIFY ROW_NUMBER() OVER (PARTITION BY establishment_id
                            ORDER BY establishment_creation_date DESC) = 1;

