USE WAREHOUSE PARIS_WH;
USE DATABASE PARIS_IMMO;
USE SCHEMA DENORM;

--DENORMALIZATION

--This stage transforms the normalized 3NF tables (OLTP) into flat, analysis-ready OLAP tables. 

----------------PHASE 1 : Create all denormalized tables(schema only)------------------

-- CREATE DIM_DATE
CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.DIM_DATE (
    DATE_ID DATE PRIMARY KEY,
    YEAR INT,
    QUARTER INT,
    MONTH INT,
    MONTH_NAME VARCHAR,
    DAY INT,
    DAY_OF_WEEK INT,
    DAY_NAME VARCHAR
);




--CREATE DIM_GEOGRAPHY (denormalized arrondissement +neighbourhood)

CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.DIM_GEOGRAPHY (
    NEIGHBOURHOOD_ID       VARCHAR      PRIMARY KEY,
    NEIGHBOURHOOD_NAME     VARCHAR,
    ARRONDISSEMENT_CODE    INT,
    ARRONDISSEMENT_NAME    VARCHAR,
    CENTROID_LAT           FLOAT,
    CENTROID_LON           FLOAT,
    GEOMETRY_WKT           VARCHAR
);


--CREATE DIM_PERMIT TABLE

CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.DIM_PERMIT (
	PERMIT_SK INT PRIMARY KEY,    -- surrogate key(unique id)
	PERMIT_TYPE_CODE  VARCHAR(50) ,
	PERMIT_TYPE_LABEL VARCHAR(100),
	PROJECT_TYPE_CODE VARCHAR(50),
	PROJECT_TYPE_LABEL VARCHAR(100),
	PERMIT_COMBINATION_LABEL VARCHAR(200)
);


--FACT TABLES

--CREATE FACT_RENT
CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.FACT_RENT_CONTROL (
    RENT_ID VARCHAR,

    NEIGHBOURHOOD_ID NUMBER(38,0),
    NEIGHBOURHOOD_NAME VARCHAR,
    ARRONDISSEMENT_CODE NUMBER(38,0),
    

    YEAR NUMBER(38,0),
    NB_ROOMS NUMBER(38,0),

    CONSTRUCTION_PERIOD VARCHAR,
    FURNISHED_STATUS VARCHAR,

    RENT_REF FLOAT,
    RENT_REF_UPPER FLOAT,
    RENT_REF_LOWER FLOAT,

    PRIMARY KEY (RENT_ID)
);


	

--CREATE  FACT_PERMIT-UNIFIED TABLE  (denormalized both housing and nonhousing permit tables)

CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.FACT_PERMIT_UNIFIED (
    PERMIT_ID VARCHAR PRIMARY KEY,
    AUTHORIZATION_DATE DATE,
    ARRONDISSEMENT_CODE INT,
    YEAR INT,
    PERMIT_SK INT,
    HOUSING_UNITS_CREATED INT,
    SURFACE_CREATED FLOAT,
    CONSTRUCTION_PERMIT VARCHAR
);
ALTER TABLE PARIS_IMMO.DENORM.FACT_PERMIT_UNIFIED
ADD COLUMN DATE_ID NUMBER(8);   --  added for dim_date 
ALTER TABLE PARIS_IMMO.DENORM.FACT_PERMIT_UNIFIED
DROP COLUMN DATE_ID;  -- dropping it because table has authorization_date that can be linked.



--CREATE EVENT-LEVEL GRAIN COMPANY FACT (derived from FACT_COMPANY_ACTIVITY)

CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.FACT_COMPANY_EVENT (
    ESTABLISHMENT_ID           VARCHAR,
    ESTABLISHMENT_CREATION_DATE DATE,
    YEAR                       INT,
    ARRONDISSEMENT_CODE        INT,
    ACTIVITY_LABEL         VARCHAR,
    EMPLOYEE_SIZE_BRACKET      VARCHAR,
    ADMINISTRATIVE_STATUS      VARCHAR
    
);

--CREATE ACTIVITY-LEVEL YEARLY FACT(aggregated YEARL GRAIN from FACT_COMPANY_ACTIVITY, grain: Arrondissement +year + Activitycode)

CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.FACT_COMPANY_ACTIVITY_YEARLY (
    ARRONDISSEMENT_CODE INT,
    YEAR INT, 
    ACTIVITY_LABEL VARCHAR,
    ESTABLISHMENTS_COUNT INT,
    ACTIVE_ESTABLISHMENTS INT,
    CLOSED_ESTABLISHMENTS INT
);


----------------PHASE 2: POPULATE THE DENORMALIZED TABLE------------------

--POPULATE DIM_DATE TABLE
TRUNCATE TABLE PARIS_IMMO.DENORM.DIM_DATE;

INSERT INTO PARIS_IMMO.DENORM.DIM_DATE
WITH DATES AS (
    SELECT DATEADD(DAY, SEQ4(), '2020-01-01'::DATE) AS D
    FROM TABLE(GENERATOR(ROWCOUNT => 4018))
)
SELECT
    D                                     AS DATE_ID,
    YEAR(D)                               AS YEAR,
    QUARTER(D)                            AS QUARTER,
    MONTH(D)                              AS MONTH,
    TO_CHAR(D, 'MONTH')                   AS MONTH_NAME,
    DAY(D)                                AS DAY,
    DAYOFWEEK(D)                          AS DAY_OF_WEEK,
    TO_CHAR(D, 'DAY')                     AS DAY_NAME
FROM DATES
WHERE D <= '2025-12-31'::DATE;




--POPULATE DIM_GEOGRAPHY TABLE
TRUNCATE TABLE PARIS_IMMO.DENORM.DIM_GEOGRAPHY;

INSERT INTO PARIS_IMMO.DENORM.DIM_GEOGRAPHY
SELECT
    N.NEIGHBOURHOOD_ID,
    N.NEIGHBOURHOOD_NAME,
    A.ARRONDISSEMENT_CODE,
    A.ARRONDISSEMENT_NAME,
    N.CENTROID_LAT,
    N.CENTROID_LON,
    N.GEOMETRY_WKT
FROM PARIS_IMMO.NORMALIZED.DIM_NEIGHBOURHOOD N
JOIN PARIS_IMMO.NORMALIZED.DIM_ARRONDISSEMENT A
    ON N.ARRONDISSEMENT_CODE = A.ARRONDISSEMENT_CODE;



--POPULATE DIM_PERMIT TABLE
TRUNCATE TABLE PARIS_IMMO.DENORM.DIM_PERMIT;

INSERT INTO PARIS_IMMO.DENORM.DIM_PERMIT
SELECT
	ROW_NUMBER() OVER (ORDER BY P.PERMIT_TYPE, PR.PROJECT_TYPE) AS PERMIT_SK,
	P.PERMIT_TYPE,
	P.PERMIT_TYPE_LABEL,
	PR.PROJECT_TYPE,
	PR.PROJECT_TYPE_LABEL,
	P.PERMIT_TYPE_LABEL || ' - ' || PR.PROJECT_TYPE_LABEL
FROM
	(SELECT DISTINCT PERMIT_TYPE, PERMIT_TYPE_LABEL FROM PARIS_IMMO.NORMALIZED.PERMIT_TYPE_LOOKUP) P
CROSS JOIN
	(SELECT DISTINCT PROJECT_TYPE, PROJECT_TYPE_LABEL FROM PARIS_IMMO.NORMALIZED.PROJECT_TYPE_LOOKUP) PR;


--POPULATE FACT_RENT
TRUNCATE TABLE PARIS_IMMO.DENORM.FACT_RENT_CONTROL;
INSERT INTO PARIS_IMMO.DENORM.FACT_RENT_CONTROL
SELECT
    R.RENT_ID,

    R.NEIGHBOURHOOD_ID,
    N.NEIGHBOURHOOD_NAME,
    N.ARRONDISSEMENT_CODE,
   

    R.YEAR,
    R.NB_ROOMS,

    C.CONSTRUCTION_PERIOD_LABEL AS CONSTRUCTION_PERIOD,
    F.FURNISHED_STATUS_LABEL AS FURNISHED_STATUS,

    R.RENT_REF,
    R.RENT_REF_UPPER,
    R.RENT_REF_LOWER

FROM PARIS_IMMO.NORMALIZED.FACT_RENT R

LEFT JOIN PARIS_IMMO.NORMALIZED.DIM_NEIGHBOURHOOD N
    ON R.NEIGHBOURHOOD_ID = N.NEIGHBOURHOOD_ID

LEFT JOIN PARIS_IMMO.NORMALIZED.DIM_CONSTRUCTION_PERIOD C
    ON R.CONSTRUCTION_PERIOD_ID = C.CONSTRUCTION_PERIOD_ID

LEFT JOIN PARIS_IMMO.NORMALIZED.DIM_FURNISHED_STATUS F
    ON R.FURNISHED_STATUS_ID = F.FURNISHED_STATUS_ID;

--POPULATE FACT_PERMIT_UNIFIED TABLE

-- FROM HOUSING PERMIT
TRUNCATE TABLE PARIS_IMMO.DENORM.FACT_PERMIT_UNIFIED;

INSERT INTO PARIS_IMMO.DENORM.FACT_PERMIT_UNIFIED
SELECT
    h.PERMIT_ID,
    h.AUTHORIZATION_DATE,
    h.ARRONDISSEMENT_CODE,
    h.YEAR,
    d.PERMIT_SK,
    h.HOUSING_UNITS_CREATED,
    h.SURFACE_CREATED,
    'HOUSING' AS CONSTRUCTION_PERMIT
FROM PARIS_IMMO.NORMALIZED.FACT_HOUSING_PERMIT h
JOIN PARIS_IMMO.DENORM.DIM_PERMIT d 
ON h.PERMIT_TYPE = d.PERMIT_TYPE_CODE AND
h.PROJECT_TYPE = d.PROJECT_TYPE_CODE;



-- FROM NONHOUSING PERMIT


INSERT INTO PARIS_IMMO.DENORM.FACT_PERMIT_UNIFIED
SELECT
    n.PERMIT_ID,
    n.AUTHORIZATION_DATE,
    n.ARRONDISSEMENT_CODE,
    n.YEAR,
    d.PERMIT_SK,
    NULL AS HOUSING_UNITS_CREATED,
    n.SURFACE_CREATED,
    'NON-HOUSING' AS CONSTRUCTION_PERMIT
FROM PARIS_IMMO.NORMALIZED.FACT_NONHOUSING_PERMIT n
JOIN PARIS_IMMO.DENORM.DIM_PERMIT d 
ON n.PERMIT_TYPE = d.PERMIT_TYPE_CODE AND
n.PROJECT_TYPE = d.PROJECT_TYPE_CODE;


--POPULATE EVENT-LEVEL TABLE
TRUNCATE TABLE PARIS_IMMO.DENORM.FACT_COMPANY_EVENT;

INSERT INTO PARIS_IMMO.DENORM.FACT_COMPANY_EVENT
SELECT
    F.ESTABLISHMENT_ID,
    F.ESTABLISHMENT_CREATION_DATE,
    F.YEAR,
    F.ARRONDISSEMENT_CODE,
    A.ACTIVITY_LABEL ,
    F.EMPLOYEE_SIZE_BRACKET,
    F.ADMINISTRATIVE_STATUS
FROM PARIS_IMMO.NORMALIZED.FACT_COMPANY_ACTIVITY F
JOIN PARIS_IMMO.NORMALIZED.DIM_ACTIVITY A 
    ON F.MAIN_ACTIVITY_CODE = A.MAIN_ACTIVITY_CODE
;


--POPULATE ACTIVITY YEARLY
TRUNCATE TABLE PARIS_IMMO.DENORM.FACT_COMPANY_ACTIVITY_YEARLY;

INSERT INTO PARIS_IMMO.DENORM.FACT_COMPANY_ACTIVITY_YEARLY
SELECT
    F.ARRONDISSEMENT_CODE,
    F.YEAR,
    A.ACTIVITY_LABEL,

    /* Total establishments */
    COUNT(DISTINCT F.ESTABLISHMENT_ID) AS ESTABLISHMENTS_COUNT,

    /* Active establishments */
    COUNT(DISTINCT CASE 
        WHEN F.ADMINISTRATIVE_STATUS = 'Active' 
        THEN F.ESTABLISHMENT_ID 
    END) AS ACTIVE_ESTABLISHMENTS,

    /* Closed establishments (based on status, not YEAR_CLOSED) */
    COUNT(DISTINCT CASE 
        WHEN F.ADMINISTRATIVE_STATUS = 'Closed' 
        THEN F.ESTABLISHMENT_ID 
    END) AS CLOSED_ESTABLISHMENTS

FROM PARIS_IMMO.NORMALIZED.FACT_COMPANY_ACTIVITY F
JOIN PARIS_IMMO.NORMALIZED.DIM_ACTIVITY A 
    ON F.MAIN_ACTIVITY_CODE = A.MAIN_ACTIVITY_CODE

GROUP BY
    F.ARRONDISSEMENT_CODE,
    F.YEAR,
    A.ACTIVITY_LABEL;



----------------PHASE 3: DIRECT COPY TABLE ------------------


--FACT_DVF
CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.FACT_DVF AS
SELECT * FROM PARIS_IMMO.NORMALIZED.FACT_TRANSACTION;


--FACT_POPULATION

CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.FACT_POPULATION AS
SELECT * FROM PARIS_IMMO.NORMALIZED.FACT_GROWTH;

--DIM_ACTIVITY_LABEL
CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.DIM_ACTIVITY_LABEL AS
SELECT 
	MAIN_ACTIVITY_CODE,
ACTIVITY_LABEL
FROM PARIS_IMMO.NORMALIZED.DIM_ACTIVITY;

--DIM_YEAR (shared dimension with all fact tables)

CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.DIM_YEAR AS
SELECT * FROM PARIS_IMMO.NORMALIZED.DIM_YEAR;

----------------PHASE 4: DERIVE TABLE ------------------

--Dim_District  ( extract the unique arrondissement level. This is extracted because fact tables are at different granularity. It acts a junction table to mantain 1:M joins)
CREATE OR REPLACE TABLE PARIS_IMMO.DENORM.DIM_DISTRICT AS
SELECT DISTINCT
	ARRONDISSEMENT_CODE,
	ARRONDISSEMENT_NAME
 FROM PARIS_IMMO.DENORM.DIM_GEOGRAPHY;

ALTER TABLE PARIS_IMMO.DENORM.DIM_DISTRICT
ADD PRIMARY KEY (ARRONDISSEMENT_CODE);





