-- EXAMPLE QUERIES FOR MIXED GRAIN
SELECT * FROM dim_geography;
SELECT NEIGHBOURHOOD_ID, COUNT(*)
FROM PARIS_IMMO.DENORM.DIM_GEOGRAPHY
GROUP BY NEIGHBOURHOOD_ID
HAVING COUNT(*) > 1;

CREATE OR REPLACE VIEW rent_by_district AS
SELECT 
    g.arrondissement_code,
    SUM(r.rent_ref) AS total_rent
FROM fact_rent_control r
JOIN dim_geography g 
    ON r.neighbourhood_id = g.neighbourhood_id
GROUP BY g.arrondissement_code;

SELECT *
FROM rent_by_district r
JOIN fact_population p USING (arrondissement_code);

select closed_establishments from fact_company_activity_yearly
where year = '2020'

SELECT
    YEAR_CLOSED,
    COUNT(DISTINCT ESTABLISHMENT_ID) AS closed_count
FROM PARIS_IMMO.NORMALIZED.FACT_COMPANY_ACTIVITY
WHERE YEAR_CLOSED IS NOT NULL
GROUP BY YEAR_CLOSED
ORDER BY YEAR_CLOSED;

SELECT
    YEAR,
    ADMINISTRATIVE_STATUS,
    COUNT(DISTINCT ESTABLISHMENT_ID) AS establishment_count
FROM PARIS_IMMO.NORMALIZED.FACT_COMPANY_ACTIVITY
GROUP BY
    YEAR,
    ADMINISTRATIVE_STATUS
ORDER BY
    YEAR,
    ADMINISTRATIVE_STATUS;


SELECT
    YEAR,
    ESTABLISHMENT_ID,
    COUNT(DISTINCT MAIN_ACTIVITY_CODE) AS activity_count
FROM PARIS_IMMO.NORMALIZED.FACT_COMPANY_ACTIVITY
GROUP BY YEAR, ESTABLISHMENT_ID
HAVING COUNT(DISTINCT MAIN_ACTIVITY_CODE) > 1
LIMIT 50;

SELECT
    YEAR,
    ESTABLISHMENT_ID,
    COUNT(DISTINCT ARRONDISSEMENT_CODE) AS arrondissement_count
FROM PARIS_IMMO.NORMALIZED.FACT_COMPANY_ACTIVITY
GROUP BY YEAR, ESTABLISHMENT_ID
HAVING COUNT(DISTINCT ARRONDISSEMENT_CODE) > 1;

