name: CI - SQL Project Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository files
        run: |
          find . -maxdepth 3 -type f

      - name: Check required SQL files exist
        run: |
          test -f sql/_01_raw_layer.sql
          test -f sql/_02_Normalized_layer.sql
          test -f sql/_03_Denormalized_layer.sql

      - name: Check SQL files are not empty
        run: |
          test -s sql/_01_raw_layer.sql
          test -s sql/_02_Normalized_layer.sql
          test -s sql/_03_Denormalized_layer.sql